Repository pagopa/pagopa-biz-events-service, pull requests merged in 2024-09, with the labels that each got.

#85 [PAGOPA-1999] New path paid notice disable
  openapi/openapi.json
  openapi/openapi_ec.json
  openapi/openapi_helpdesk.json
  openapi/openapi_io.json
  src/main/java/it/gov/pagopa/bizeventsservice/controller/IPaidNoticeController.java
  src/main/java/it/gov/pagopa/bizeventsservice/controller/ITransactionController.java
  src/main/java/it/gov/pagopa/bizeventsservice/controller/impl/PaidNoticeController.java
  src/test/java/it/gov/pagopa/bizeventsservice/controller/PaidNoticeControllerTest.java
  src/test/java/it/gov/pagopa/bizeventsservice/controller/PaymentsControllerTest.java
  src/test/resources/receipts/getOrganizationReceipt.json
Labels: enhancement, size/large, minor

#84 feat: [PAGOPA-2070] - remove cart merge
  src/main/java/it/gov/pagopa/bizeventsservice/model/response/Debtor.java
  src/main/java/it/gov/pagopa/bizeventsservice/service/impl/TransactionService.java
Labels: size/small, patch

#88 feat: [PagoPa-1997] - paid notice details
  openapi/openapi.json
  openapi/openapi_ec.json
  openapi/openapi_helpdesk.json
  openapi/openapi_io.json
  src/main/java/it/gov/pagopa/bizeventsservice/Application.java
  src/main/java/it/gov/pagopa/bizeventsservice/config/RedisConfig.java
  src/main/java/it/gov/pagopa/bizeventsservice/controller/IPaidNoticeController.java
  src/main/java/it/gov/pagopa/bizeventsservice/controller/ITransactionController.java
  src/main/java/it/gov/pagopa/bizeventsservice/controller/impl/PaidNoticeController.java
  src/main/java/it/gov/pagopa/bizeventsservice/controller/impl/TransactionController.java
  src/main/java/it/gov/pagopa/bizeventsservice/entity/view/UserDetail.java
  src/main/java/it/gov/pagopa/bizeventsservice/mapper/ConvertViewsToTransactionDetailResponse.java
  src/main/java/it/gov/pagopa/bizeventsservice/model/response/paidnotice/CartItem.java
  src/main/java/it/gov/pagopa/bizeventsservice/model/response/paidnotice/InfoNotice.java
  src/main/java/it/gov/pagopa/bizeventsservice/model/response/paidnotice/NoticeDetailResponse.java
  src/main/java/it/gov/pagopa/bizeventsservice/repository/redis/RedisRepository.java
  src/main/java/it/gov/pagopa/bizeventsservice/service/ITransactionService.java
  src/main/java/it/gov/pagopa/bizeventsservice/service/impl/TransactionService.java
  src/main/java/it/gov/pagopa/bizeventsservice/util/Constants.java
  src/main/resources/application-dev.properties
  src/main/resources/application.properties
  src/test/java/it/gov/pagopa/bizeventsservice/controller/PaidNoticeControllerTest.java
  src/test/java/it/gov/pagopa/bizeventsservice/controller/TransactionControllerTest.java
  src/test/java/it/gov/pagopa/bizeventsservice/service/TransactionServiceTest.java
  src/test/resources/application.properties
  src/test/resources/biz-events/paidNoticeDetails.json
Labels: size/large

#86 [PAGOPA-1998] PDF new path
  openapi/openapi.json
  openapi/openapi_ec.json
  openapi/openapi_helpdesk.json
  openapi/openapi_io.json
  src/main/java/it/gov/pagopa/bizeventsservice/config/ContentNegotiationConf.java
  src/main/java/it/gov/pagopa/bizeventsservice/controller/IPaidNoticeController.java
  src/main/java/it/gov/pagopa/bizeventsservice/controller/ITransactionController.java
  src/main/java/it/gov/pagopa/bizeventsservice/controller/impl/PaidNoticeController.java
  src/main/java/it/gov/pagopa/bizeventsservice/exception/ErrorHandler.java
  src/main/java/it/gov/pagopa/bizeventsservice/mapper/ConvertViewsToTransactionDetailResponse.java
  src/main/java/it/gov/pagopa/bizeventsservice/service/ITransactionService.java
  src/main/java/it/gov/pagopa/bizeventsservice/service/impl/TransactionService.java
  src/test/java/it/gov/pagopa/bizeventsservice/controller/BaseControllerTest.java
  src/test/java/it/gov/pagopa/bizeventsservice/controller/PaidNoticeControllerTest.java
  src/test/java/it/gov/pagopa/bizeventsservice/controller/PaymentsControllerTest.java
  src/test/java/it/gov/pagopa/bizeventsservice/controller/TransactionControllerTest.java
  src/test/java/it/gov/pagopa/bizeventsservice/exception/ErrorHandlerTest.java
  src/test/java/it/gov/pagopa/bizeventsservice/service/BizEventsServiceTest.java
  src/test/java/it/gov/pagopa/bizeventsservice/service/TransactionServiceTest.java
  src/test/java/it/gov/pagopa/bizeventsservice/util/BizEventGenerator.java
  src/test/java/it/gov/pagopa/bizeventsservice/util/MockConfiguration.java
  src/test/java/it/gov/pagopa/bizeventsservice/util/UtilTest.java
  src/test/java/it/gov/pagopa/bizeventsservice/util/ViewGenerator.java
Labels: enhancement, size/large, minor

#89 fix: [PQ-151] - email field name
  openapi/openapi.json
  openapi/openapi_ec.json
  openapi/openapi_helpdesk.json
  openapi/openapi_io.json
  src/main/java/it/gov/pagopa/bizeventsservice/entity/Debtor.java
  src/main/java/it/gov/pagopa/bizeventsservice/entity/Payer.java
  src/main/java/it/gov/pagopa/bizeventsservice/model/response/CtReceiptModelResponse.java
  src/main/java/it/gov/pagopa/bizeventsservice/model/response/Debtor.java
  src/main/java/it/gov/pagopa/bizeventsservice/model/response/Payer.java
  src/test/resources/biz-events/bizEvent.json
  src/test/resources/biz-events/bizEvent_duplicate.json
  src/test/resources/receipts/getOrganizationReceipt.json
Labels: size/large, patch

#92 feat: [PagoPA-2083] Api integration test
  .github/workflows/code_review.yml
  .github/workflows/integration_test.yml
  docker/run_docker.sh
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  integration-test/src/config/.env.dev
  integration-test/src/config/.env.local
  integration-test/src/config/.env.uat
  integration-test/src/step_definitions/support/bizeventservice_client.js
  integration-test/src/step_definitions/support/common.js
  integration-test/src/step_definitions/support/organizationsreceipt_steps.js
  openapi/openapi.json
  openapi/openapi_ec.json
  openapi/openapi_helpdesk.json
  openapi/openapi_io.json
  openapi/openapi_io_patch.json
  openapi/openapi_io_patch_lap.json
  pom.xml
  src/main/java/it/gov/pagopa/bizeventsservice/service/impl/TransactionService.java
Labels: size/small, patch

#93 bug: [PagoPa-2166] - fix list info for cart
  src/main/java/it/gov/pagopa/bizeventsservice/entity/view/BizEventsViewGeneral.java
  src/main/java/it/gov/pagopa/bizeventsservice/mapper/ConvertViewsToTransactionDetailResponse.java
  src/main/java/it/gov/pagopa/bizeventsservice/service/impl/TransactionService.java
  src/test/java/it/gov/pagopa/bizeventsservice/service/TransactionServiceTest.java
Labels: size/small, minor
