Repository pagopa/pagopa-biz-events-service, pull requests merged in 2024-01, with the labels that each got.

#30 PAGOPA-1404 adding new biz api fiscalCode-iur
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  pom.xml
  src/main/java/it/gov/pagopa/bizeventsservice/controller/IPaymentsController.java
  src/main/java/it/gov/pagopa/bizeventsservice/controller/impl/PaymentsController.java
  src/main/java/it/gov/pagopa/bizeventsservice/exception/AppError.java
  src/main/java/it/gov/pagopa/bizeventsservice/repository/BizEventsRepository.java
  src/main/java/it/gov/pagopa/bizeventsservice/service/IBizEventsService.java
  src/main/java/it/gov/pagopa/bizeventsservice/service/impl/BizEventsService.java
  src/main/java/it/gov/pagopa/bizeventsservice/util/Constants.java
  src/test/java/it/gov/pagopa/bizeventsservice/controller/PaymentsControllerTest.java
  src/test/java/it/gov/pagopa/bizeventsservice/service/BizEventsServiceTest.java
Labels: enhancement, size/small

#33 PAGOPA-1454 moving to java 17
  .github/workflows/code_review.yml
  .github/workflows/update_code.yml
  Dockerfile
  README.md
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  pom.xml
Labels: enhancement, size/small

#32 [PRDP-316] feat: Defined TransactionList & TransactionDetails API
  src/main/java/it/gov/pagopa/bizeventsservice/controller/ITransactionController.java
  src/main/java/it/gov/pagopa/bizeventsservice/controller/impl/TransactionController.java
  src/main/java/it/gov/pagopa/bizeventsservice/entity/InfoTransaction.java
  src/main/java/it/gov/pagopa/bizeventsservice/entity/PaymentInfo.java
  src/main/java/it/gov/pagopa/bizeventsservice/entity/Transaction.java
  src/main/java/it/gov/pagopa/bizeventsservice/entity/TransactionDetails.java
  src/main/java/it/gov/pagopa/bizeventsservice/entity/TransactionPsp.java
  src/main/java/it/gov/pagopa/bizeventsservice/exception/AppError.java
  src/main/java/it/gov/pagopa/bizeventsservice/mapper/ConvertBizEventListToTransactionDetailResponse.java
  src/main/java/it/gov/pagopa/bizeventsservice/model/response/transaction/CartItem.java
  src/main/java/it/gov/pagopa/bizeventsservice/model/response/transaction/InfoTransaction.java
  src/main/java/it/gov/pagopa/bizeventsservice/model/response/transaction/TransactionDetailResponse.java
  src/main/java/it/gov/pagopa/bizeventsservice/model/response/transaction/TransactionListItem.java
  src/main/java/it/gov/pagopa/bizeventsservice/model/response/transaction/UserDetail.java
  src/main/java/it/gov/pagopa/bizeventsservice/model/response/transaction/WalletInfo.java
  src/main/java/it/gov/pagopa/bizeventsservice/model/response/transaction/enumeration/OriginType.java
  src/main/java/it/gov/pagopa/bizeventsservice/model/response/transaction/enumeration/PaymentMethodType.java
  src/main/java/it/gov/pagopa/bizeventsservice/repository/BizEventsRepository.java
  src/main/java/it/gov/pagopa/bizeventsservice/service/ITransactionService.java
  src/main/java/it/gov/pagopa/bizeventsservice/service/impl/TransactionService.java
  src/main/java/it/gov/pagopa/bizeventsservice/util/Constants.java
  src/main/resources/application.properties
  src/test/java/it/gov/pagopa/bizeventsservice/controller/TransactionControllerTest.java
  src/test/java/it/gov/pagopa/bizeventsservice/service/TransactionServiceTest.java
  src/test/java/it/gov/pagopa/bizeventsservice/util/BizEventGenerator.java
  src/test/resources/application.properties
  src/test/resources/biz-events/getTransactionList.json
  src/test/resources/biz-events/transactionCartItems.json
  src/test/resources/biz-events/transactionDetails.json
  src/test/resources/biz-events/transactionListCart.json
  src/test/resources/biz-events/transactionListNoCart.json
Labels: enhancement, size/large, minor

#31 [PRDP-318] feat: Setup integration test for transaction APIs
  .github/workflows/code_review.yml
  .github/workflows/integration_test.yml
  .gitignore
  .identity/00_data.tf
  .identity/03_github_environment.tf
  integration-test/src/features/organizationsreceipt.feature
  integration-test/src/package.json
  integration-test/src/step_definitions/support/biz_events_cosmosdb_client.js
  integration-test/src/step_definitions/support/bizeventservice_client.js
  integration-test/src/step_definitions/support/common.js
  integration-test/src/step_definitions/support/organizationsreceipt_steps.js
Labels: skip

#34 [PRDP-335] feat: Add checks on remittance info
  src/main/java/it/gov/pagopa/bizeventsservice/mapper/ConvertBizEventListToTransactionDetailResponse.java
  src/test/java/it/gov/pagopa/bizeventsservice/service/TransactionServiceTest.java
Labels: size/small, patch
