Repository pagopa/pagopa-biz-events-service, pull requests merged in 2024-05, with the labels that each got.

#58 PAGOPA-1681 adding testResources in pom.xml file
  openapi/openapi.json
  openapi/openapi_ec.json
  openapi/openapi_helpdesk.json
  openapi/openapi_io.json
  pom.xml
Labels: bug, size/large

#59 PAGOPA-1724 adding missing fields
  src/main/java/it/gov/pagopa/bizeventsservice/entity/DebtorPosition.java
  src/main/java/it/gov/pagopa/bizeventsservice/model/response/enumeration/UserType.java
Labels: bug, size/small, patch

#60 feat: [PagoPA-1741] - get pdf receipt
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  openapi/openapi_ec.json
  openapi/openapi_helpdesk.json
  openapi/openapi_io.json
  pom.xml
  src/main/java/it/gov/pagopa/bizeventsservice/Application.java
  src/main/java/it/gov/pagopa/bizeventsservice/client/IReceiptPDFClient.java
  src/main/java/it/gov/pagopa/bizeventsservice/config/feign/AuthFeignConfig.java
  src/main/java/it/gov/pagopa/bizeventsservice/config/feign/PDFReceiptFeignConfig.java
  src/main/java/it/gov/pagopa/bizeventsservice/controller/ITransactionController.java
  src/main/java/it/gov/pagopa/bizeventsservice/controller/impl/TransactionController.java
  src/main/java/it/gov/pagopa/bizeventsservice/mapper/ConvertViewsToTransactionDetailResponse.java
  src/main/java/it/gov/pagopa/bizeventsservice/model/response/Attachment.java
  src/main/java/it/gov/pagopa/bizeventsservice/model/response/AttachmentsDetailsResponse.java
  src/main/java/it/gov/pagopa/bizeventsservice/model/response/transaction/TransactionListItem.java
  src/main/resources/application-dev.properties
  src/main/resources/application.properties
  src/test/java/it/gov/pagopa/bizeventsservice/controller/TransactionControllerTest.java
  src/test/resources/application.properties
Labels: size/large, minor

#61 feat: [PagoPa-1763] - transaction response adjustment
  openapi/openapi.json
  openapi/openapi_ec.json
  openapi/openapi_helpdesk.json
  openapi/openapi_io.json
  src/main/java/it/gov/pagopa/bizeventsservice/controller/ITransactionController.java
  src/main/java/it/gov/pagopa/bizeventsservice/controller/impl/TransactionController.java
  src/main/java/it/gov/pagopa/bizeventsservice/entity/view/BizEventsViewUser.java
  src/main/java/it/gov/pagopa/bizeventsservice/entity/view/WalletInfo.java
  src/main/java/it/gov/pagopa/bizeventsservice/mapper/ConvertViewsToTransactionDetailResponse.java
  src/main/java/it/gov/pagopa/bizeventsservice/model/response/transaction/InfoTransactionView.java
  src/main/java/it/gov/pagopa/bizeventsservice/model/response/transaction/TransactionDetailResponse.java
  src/main/java/it/gov/pagopa/bizeventsservice/model/response/transaction/TransactionListItem.java
  src/main/java/it/gov/pagopa/bizeventsservice/model/response/transaction/TransactionListWrapResponse.java
  src/main/java/it/gov/pagopa/bizeventsservice/service/impl/TransactionService.java
  src/test/java/it/gov/pagopa/bizeventsservice/service/TransactionServiceTest.java
  src/test/java/it/gov/pagopa/bizeventsservice/util/ViewGenerator.java
Labels: size/large, patch

#65 chore: Remove pdf for io
  openapi/openapi_io_patch.json
Labels: size/large
