Repository pagopa/pagopa-biz-events-service, pull requests merged in 2024-10, with the labels that each got.

#94 feat: [PAGOPA-2168] log optimization
  .github/workflows/release_deploy.yml
  Dockerfile
  docker/applicationinsights.json
  docker/run_docker.sh
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  openapi/openapi_ec.json
  openapi/openapi_helpdesk.json
  openapi/openapi_io.json
  openapi/openapi_io_patch.json
  openapi/openapi_io_patch_lap.json
  pom.xml
  src/main/java/it/gov/pagopa/bizeventsservice/config/LoggingAspect.java
  src/main/java/it/gov/pagopa/bizeventsservice/exception/AppError.java
  src/main/java/it/gov/pagopa/bizeventsservice/util/CommonUtil.java
  src/main/resources/logback-spring.xml
  src/test/java/it/gov/pagopa/bizeventsservice/util/CommonUtilTest.java
Labels: size/large, patch

#95 [PAGOPA-2258] chore(sampling): bump image Dockerfile
  .gitignore
  Dockerfile
  docker/applicationinsights.json
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  openapi/openapi_ec.json
  openapi/openapi_helpdesk.json
  openapi/openapi_io.json
  openapi/openapi_io_patch.json
  openapi/openapi_io_patch_lap.json
  pom.xml
  src/main/java/it/gov/pagopa/bizeventsservice/config/LoggingAspect.java
Labels: size/small

#96 fix: remove otel env vars
  Dockerfile
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  openapi/openapi_ec.json
  openapi/openapi_helpdesk.json
  openapi/openapi_io.json
  openapi/openapi_io_patch.json
  openapi/openapi_io_patch_lap.json
  pom.xml
  src/main/resources/logback-spring.xml
Labels: size/small

#97 docker
  Dockerfile
Labels: size/small

#98 BUG: [PAGOPA-2260] - issue cart
  src/main/java/it/gov/pagopa/bizeventsservice/controller/impl/PaidNoticeController.java
  src/main/java/it/gov/pagopa/bizeventsservice/exception/AppError.java
  src/main/java/it/gov/pagopa/bizeventsservice/repository/BizEventsViewUserRepository.java
  src/main/java/it/gov/pagopa/bizeventsservice/service/ITransactionService.java
  src/main/java/it/gov/pagopa/bizeventsservice/service/impl/TransactionService.java
  src/test/java/it/gov/pagopa/bizeventsservice/controller/PaidNoticeControllerTest.java
  src/test/java/it/gov/pagopa/bizeventsservice/service/TransactionServiceTest.java
Labels: bug, size/small, patch
