Repository pagopa/pagopa-biz-events-service, pull requests merged in 2024-02, with the labels that each got.

#36 [PRDP-356] chore: Review openapi spec generation biz service
  openapi/openapi.json
  src/main/java/it/gov/pagopa/bizeventsservice/controller/IBizEventController.java
  src/main/java/it/gov/pagopa/bizeventsservice/controller/ITransactionController.java
  src/main/java/it/gov/pagopa/bizeventsservice/controller/impl/TransactionController.java
  src/main/java/it/gov/pagopa/bizeventsservice/service/ITransactionService.java
  src/main/java/it/gov/pagopa/bizeventsservice/service/impl/TransactionService.java
Labels: size/small

#37 [PRDP-358] feat: Rework Transaction Detail API
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  integration-test/src/config/.env.dev
  integration-test/src/config/.env.local
  integration-test/src/config/.env.uat
  src/main/java/it/gov/pagopa/bizeventsservice/controller/ITransactionController.java
  src/main/java/it/gov/pagopa/bizeventsservice/entity/view/BizEventsViewCart.java
  src/main/java/it/gov/pagopa/bizeventsservice/entity/view/BizEventsViewGeneral.java
  src/main/java/it/gov/pagopa/bizeventsservice/entity/view/BizEventsViewUser.java
  src/main/java/it/gov/pagopa/bizeventsservice/entity/view/UserDetail.java
  src/main/java/it/gov/pagopa/bizeventsservice/entity/view/WalletInfo.java
  src/main/java/it/gov/pagopa/bizeventsservice/entity/view/enumeration/OriginType.java
  src/main/java/it/gov/pagopa/bizeventsservice/entity/view/enumeration/PaymentMethodType.java
  src/main/java/it/gov/pagopa/bizeventsservice/exception/AppError.java
  src/main/java/it/gov/pagopa/bizeventsservice/mapper/ConvertBizEventListToTransactionDetailResponse.java
  src/main/java/it/gov/pagopa/bizeventsservice/mapper/ConvertViewsToTransactionDetailResponse.java
  src/main/java/it/gov/pagopa/bizeventsservice/model/response/transaction/CartItem.java
  src/main/java/it/gov/pagopa/bizeventsservice/model/response/transaction/InfoTransaction.java
  src/main/java/it/gov/pagopa/bizeventsservice/model/response/transaction/TransactionDetailResponse.java
  src/main/java/it/gov/pagopa/bizeventsservice/model/response/transaction/TransactionListItem.java
  src/main/java/it/gov/pagopa/bizeventsservice/repository/BizEventsViewCartRepository.java
  src/main/java/it/gov/pagopa/bizeventsservice/repository/BizEventsViewGeneralRepository.java
  src/main/java/it/gov/pagopa/bizeventsservice/repository/BizEventsViewUserRepository.java
  src/main/java/it/gov/pagopa/bizeventsservice/service/impl/TransactionService.java
  src/main/java/it/gov/pagopa/bizeventsservice/util/Constants.java
  src/main/resources/application-dev.properties
  src/main/resources/application.properties
  src/test/java/it/gov/pagopa/bizeventsservice/controller/TransactionControllerTest.java
  src/test/java/it/gov/pagopa/bizeventsservice/service/TransactionServiceTest.java
  src/test/java/it/gov/pagopa/bizeventsservice/util/BizEventGenerator.java
  src/test/java/it/gov/pagopa/bizeventsservice/util/MockConfiguration.java
  src/test/java/it/gov/pagopa/bizeventsservice/util/ViewGenerator.java
  src/test/resources/application.properties
Labels: enhancement, size/large

#40 Pagopa 1481 sviluppo upgrade ai with java 17
  Dockerfile
Labels: enhancement, size/small

#35 PAGOPA-1475 adding iur clause
  src/main/java/it/gov/pagopa/bizeventsservice/repository/BizEventsRepository.java
Labels: size/small

#38 [PRDP-349] feat: Rework TransactionList API
  src/main/java/it/gov/pagopa/bizeventsservice/controller/ITransactionController.java
  src/main/java/it/gov/pagopa/bizeventsservice/controller/impl/TransactionController.java
  src/main/java/it/gov/pagopa/bizeventsservice/entity/view/BizEventsViewGeneral.java
  src/main/java/it/gov/pagopa/bizeventsservice/entity/view/BizEventsViewUser.java
  src/main/java/it/gov/pagopa/bizeventsservice/exception/AppError.java
  src/main/java/it/gov/pagopa/bizeventsservice/mapper/ConvertViewsToTransactionDetailResponse.java
  src/main/java/it/gov/pagopa/bizeventsservice/model/response/transaction/TransactionListResponse.java
  src/main/java/it/gov/pagopa/bizeventsservice/repository/BizEventsViewCartRepository.java
  src/main/java/it/gov/pagopa/bizeventsservice/repository/BizEventsViewGeneralRepository.java
  src/main/java/it/gov/pagopa/bizeventsservice/repository/BizEventsViewUserRepository.java
  src/main/java/it/gov/pagopa/bizeventsservice/service/ITransactionService.java
  src/main/java/it/gov/pagopa/bizeventsservice/service/impl/TransactionService.java
  src/main/java/it/gov/pagopa/bizeventsservice/util/Constants.java
  src/test/java/it/gov/pagopa/bizeventsservice/controller/TransactionControllerTest.java
  src/test/java/it/gov/pagopa/bizeventsservice/service/TransactionServiceTest.java
  src/test/java/it/gov/pagopa/bizeventsservice/util/ViewGenerator.java
Labels: enhancement, size/large

#41 [fix] Fix unit tests transactionController
  src/test/java/it/gov/pagopa/bizeventsservice/controller/TransactionControllerTest.java
Labels: size/small

#39 Prdp 359 feat add disable tx api
  src/main/java/it/gov/pagopa/bizeventsservice/controller/ITransactionController.java
  src/main/java/it/gov/pagopa/bizeventsservice/controller/impl/TransactionController.java
  src/main/java/it/gov/pagopa/bizeventsservice/exception/AppError.java
  src/main/java/it/gov/pagopa/bizeventsservice/repository/BizEventsViewUserRepository.java
  src/main/java/it/gov/pagopa/bizeventsservice/service/ITransactionService.java
  src/main/java/it/gov/pagopa/bizeventsservice/service/impl/TransactionService.java
  src/test/java/it/gov/pagopa/bizeventsservice/controller/TransactionControllerTest.java
  src/test/java/it/gov/pagopa/bizeventsservice/service/TransactionServiceTest.java
Labels: enhancement, size/small, minor

#42 [PRDP-356] feat: Updated openapi
  openapi/generate_openapi.sh
  openapi/openapi.json
  openapi/openapi_ec.json
  openapi/openapi_helpdesk.json
  openapi/openapi_io.json
  src/main/java/it/gov/pagopa/bizeventsservice/config/OpenApiConfig.java
  src/main/java/it/gov/pagopa/bizeventsservice/controller/ITransactionController.java
  src/main/resources/application.properties
  src/test/java/it/gov/pagopa/bizeventsservice/OpenApiGenerationTest.java
  src/test/resources/application.properties
Labels: size/large, patch

#43 [PRDP-363] Reworked integration tests
  integration-test/src/config/.env.dev
  integration-test/src/config/.env.local
  integration-test/src/config/.env.uat
  integration-test/src/features/organizationsreceipt.feature
  integration-test/src/step_definitions/support/biz_events_cosmosdb_client.js
  integration-test/src/step_definitions/support/bizeventservice_client.js
  integration-test/src/step_definitions/support/common.js
  integration-test/src/step_definitions/support/organizationsreceipt_steps.js
  src/main/java/it/gov/pagopa/bizeventsservice/entity/view/BizEventsViewGeneral.java
  src/main/java/it/gov/pagopa/bizeventsservice/entity/view/BizEventsViewUser.java
  src/main/java/it/gov/pagopa/bizeventsservice/exception/AppError.java
  src/main/java/it/gov/pagopa/bizeventsservice/repository/BizEventsViewCartRepository.java
  src/main/java/it/gov/pagopa/bizeventsservice/repository/BizEventsViewGeneralRepository.java
  src/main/java/it/gov/pagopa/bizeventsservice/repository/BizEventsViewUserRepository.java
  src/main/java/it/gov/pagopa/bizeventsservice/service/impl/TransactionService.java
  src/test/java/it/gov/pagopa/bizeventsservice/service/TransactionServiceTest.java
Labels: size/large, patch

#44 fix: Remove taxCode validity check
  src/main/java/it/gov/pagopa/bizeventsservice/service/impl/TransactionService.java
  src/test/java/it/gov/pagopa/bizeventsservice/service/TransactionServiceTest.java
Labels: size/small, patch

#46 fix: Pipe
  .github/workflows/integration_test.yml
Labels: size/small

#47 chore: Fix integ test
  integration-test/src/config/.env.dev
  integration-test/src/config/.env.local
  integration-test/src/config/.env.uat
  integration-test/src/step_definitions/support/bizeventservice_client.js
Labels: size/small

#48 reviewed openapi
  openapi/openapi.json
  openapi/openapi_ec.json
  openapi/openapi_helpdesk.json
  openapi/openapi_io.json
  src/main/java/it/gov/pagopa/bizeventsservice/controller/ITransactionController.java
  src/main/resources/application.properties
  src/test/resources/application.properties
Labels: size/large, patch
