Repository pagopa/pagopa-biz-events-service, pull requests merged in 2024-06, with the labels that each got.

#68 [PAGOPA-1748] check cart items in which the user is debtor
  src/main/java/it/gov/pagopa/bizeventsservice/mapper/ConvertViewsToTransactionDetailResponse.java
Labels: size/small, patch

#69 chore: Add self_hosted_runner_image_tag
  .github/workflows/deploy_with_github_runner.yml
Labels: patch

#70 feat: [PagoPa-1797] paging and caching
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  pom.xml
  src/main/java/it/gov/pagopa/bizeventsservice/Application.java
  src/main/java/it/gov/pagopa/bizeventsservice/config/RedisConfig.java
  src/main/java/it/gov/pagopa/bizeventsservice/controller/ITransactionController.java
  src/main/java/it/gov/pagopa/bizeventsservice/controller/impl/TransactionController.java
  src/main/java/it/gov/pagopa/bizeventsservice/entity/view/BizEventsViewUser.java
  src/main/java/it/gov/pagopa/bizeventsservice/mapper/ConvertViewsToTransactionDetailResponse.java
  src/main/java/it/gov/pagopa/bizeventsservice/model/PageInfo.java
  src/main/java/it/gov/pagopa/bizeventsservice/model/response/transaction/TransactionListResponse.java
  src/main/java/it/gov/pagopa/bizeventsservice/model/response/transaction/TransactionListWrapResponse.java
  src/main/java/it/gov/pagopa/bizeventsservice/repository/BizEventsViewUserRepository.java
  src/main/java/it/gov/pagopa/bizeventsservice/repository/redis/RedisRepository.java
  src/main/java/it/gov/pagopa/bizeventsservice/service/ITransactionService.java
  src/main/java/it/gov/pagopa/bizeventsservice/service/impl/TransactionService.java
  src/main/java/it/gov/pagopa/bizeventsservice/util/Constants.java
  src/main/java/it/gov/pagopa/bizeventsservice/util/Util.java
  src/main/resources/application-dev.properties
  src/main/resources/application.properties
  src/test/java/it/gov/pagopa/bizeventsservice/controller/TransactionControllerTest.java
  src/test/java/it/gov/pagopa/bizeventsservice/service/TransactionServiceTest.java
  src/test/java/it/gov/pagopa/bizeventsservice/util/ViewGenerator.java
  src/test/resources/application.properties
Labels: size/large, patch

#71 chore: Upd openapi
  openapi/openapi.json
  openapi/openapi_ec.json
  openapi/openapi_helpdesk.json
  openapi/openapi_io.json
  openapi/openapi_io_patch.json
Labels: size/large, skip

#72 [PagoPa-1838] update get pdf receipt
  src/main/java/it/gov/pagopa/bizeventsservice/controller/impl/TransactionController.java
  src/main/java/it/gov/pagopa/bizeventsservice/model/response/Attachment.java
  src/main/java/it/gov/pagopa/bizeventsservice/model/response/AttachmentsDetailsResponse.java
  src/main/java/it/gov/pagopa/bizeventsservice/model/response/enumeration/StatusType.java
  src/main/java/it/gov/pagopa/bizeventsservice/service/ITransactionService.java
  src/main/java/it/gov/pagopa/bizeventsservice/service/impl/TransactionService.java
  src/main/resources/application-dev.properties
  src/test/java/it/gov/pagopa/bizeventsservice/controller/TransactionControllerTest.java
  src/test/java/it/gov/pagopa/bizeventsservice/service/TransactionServiceTest.java
Labels: size/small, patch

#76 bug: [PagoPa-1847]: fixed cache transaction list
  src/main/java/it/gov/pagopa/bizeventsservice/model/filterandorder/Order.java
  src/main/java/it/gov/pagopa/bizeventsservice/model/filterandorder/OrderType.java
  src/main/java/it/gov/pagopa/bizeventsservice/service/impl/TransactionService.java
  src/main/java/it/gov/pagopa/bizeventsservice/util/Util.java
  src/test/java/it/gov/pagopa/bizeventsservice/controller/PaymentsControllerTest.java
  src/test/java/it/gov/pagopa/bizeventsservice/controller/TransactionControllerTest.java
  src/test/java/it/gov/pagopa/bizeventsservice/service/BizEventsServiceTest.java
  src/test/java/it/gov/pagopa/bizeventsservice/service/TransactionServiceTest.java
  src/test/java/it/gov/pagopa/bizeventsservice/util/UtilTest.java
  src/test/java/it/gov/pagopa/bizeventsservice/util/Utility.java
Labels: size/small, patch
