Repository pagopa/pagopa-biz-events-service, pull requests merged in 2025-05, with the labels that each got.

#109 chore: [PIDM-488] Implement workload identity
  .github/workflows/code_review.yml
  .github/workflows/create_dashboard.yaml
  .github/workflows/deploy_with_github_runner.yml
  .github/workflows/integration_test.yml
  .github/workflows/release_deploy.yml
  .github/workflows/report_ingestion.yml
  .identity/.terraform.lock.hcl
  .identity/00_data.tf
  .identity/03_github_environment.tf
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  openapi/openapi_ec.json
  openapi/openapi_helpdesk.json
  openapi/openapi_lap.json
  openapi/openapi_lap_jwt.json
  openapi/openapi_transaction.json
  openapi/openapi_transaction_jwt.json
  pom.xml
Labels: patch

#110 chore: Upd en github repo
  .identity/00_data.tf
  .identity/03_github_environment.tf
  .identity/99_variables.tf
Labels: size/small, patch

#112 chore: dashboard overrides
  .github/workflows/create_dashboard.yaml
  .opex/biz-service/env/prod/config.yaml
Labels: size/small
